version: "3.7"
services:
  jana:
    build: .
    command: bash
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/debian/.config/gcloud/localdev.json
    volumes:
      - ${HOME}/.aws:/home/debian/.aws  # AWS Creds
      - ${HOME}/.config/gcloud:/home/debian/.config/gcloud  # GCloud Creds
      - ./:/home/debian/jana  # This dir to workdir
